export const booksData = [
  {
    title: "قدرت عادت",
    slug: "ghodrat-e-adat",
    description:
      "این کتاب توضیح می‌دهد چگونه عادت‌ها شکل می‌گیرند و چگونه می‌توان آن‌ها را تغییر داد.",
    type: "ebook",
    categories: ["روانشناسی", "خودشناسی"],
    authors: ["چارلز داهیگ"],
    translators: ["محمدرضا آل‌خسروی"],
    publisher: "انتشارات نوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghodrat-e-adat.jpg",
    fileUrl: "",
    pages: 380,
    price: 89000,
    discountPrice: 59000,
    rating: { average: 4.5, count: 1523 },
    publishedAt: new Date("2019-06-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "اثر مرکب",
    slug: "asar-morakab",
    description:
      "کتابی درباره‌ی قدرت تصمیمات کوچک و تأثیر آن‌ها بر موفقیت‌های بزرگ.",
    type: "ebook",
    categories: ["موفقیت", "کسب و کار"],
    authors: ["دارن هاردی"],
    translators: ["لیلا فرجی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/asar-morakab.jpg",
    fileUrl: "",
    pages: 256,
    price: 120000,
    discountPrice: 99000,
    rating: { average: 4.7, count: 3104 },
    publishedAt: new Date("2020-02-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "هنر ظریف رهایی از دغدغه‌ها",
    slug: "honar-zarif-rahayi",
    description:
      "این کتاب با بیانی طنزآمیز به موضوع مدیریت دغدغه‌ها و اولویت‌بندی در زندگی می‌پردازد.",
    type: "ebook",
    categories: ["زندگی‌نامه", "روانشناسی"],
    authors: ["مارک منسون"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات میلکان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/honar-zarif.jpg",
    fileUrl: "",
    pages: 272,
    price: 105000,
    discountPrice: 84000,
    rating: { average: 4.3, count: 2489 },
    publishedAt: new Date("2018-09-01"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "بیندیشید و ثروتمند شوید",
    slug: "beyandishid-va-servatmand-shavid",
    description:
      "راهنمایی کلاسیک برای دستیابی به موفقیت مالی و شخصی از طریق اصول تفکر مثبت و هدفمندی.",
    type: "ebook",
    categories: ["کسب و کار", "موفقیت"],
    authors: ["ناپلئون هیل"],
    translators: ["مهدی قراچه‌داغی"],
    publisher: "انتشارات شبگیر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/beyandishid.jpg",
    fileUrl: "",
    pages: 320,
    price: 98000,
    discountPrice: 75000,
    rating: { average: 4.6, count: 4201 },
    publishedAt: new Date("2017-04-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "انسان در جستجوی معنا",
    slug: "ensan-dar-joostjooy-mana",
    description:
      "کتاب مشهور ویکتور فرانکل درباره تجربیات او در اردوگاه‌های کار اجباری و معنای زندگی.",
    type: "ebook",
    categories: ["فلسفه", "روانشناسی"],
    authors: ["ویکتور فرانکل"],
    translators: ["حسینعلی قراچه‌داغی"],
    publisher: "انتشارات پیام امروز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ensan-mana.jpg",
    fileUrl: "",
    pages: 220,
    price: 76000,
    discountPrice: 62000,
    rating: { average: 4.8, count: 5150 },
    publishedAt: new Date("2016-11-11"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "چهار میثاق",
    slug: "chahar-misaq",
    description:
      "راهنمایی عملی برای دستیابی به آزادی شخصی و خوشبختی بر اساس آموزه‌های باستانی تولتک‌ها.",
    type: "ebook",
    categories: ["خودشناسی", "معنوی"],
    authors: ["دون میگوئل روئیز"],
    translators: ["دل‌آرام وزیری"],
    publisher: "انتشارات آتیسا",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/chahar-misaq.jpg",
    fileUrl: "",
    pages: 160,
    price: 67000,
    discountPrice: 53000,
    rating: { average: 4.4, count: 1880 },
    publishedAt: new Date("2015-07-01"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قوی سیاه",
    slug: "ghavi-siah",
    description:
      "کتابی درباره‌ی رویدادهای پیش‌بینی‌ناپذیر و تاثیر عظیم آن‌ها بر جهان.",
    type: "ebook",
    categories: ["اقتصاد", "فلسفه"],
    authors: ["نسیم نیکلاس طالب"],
    translators: ["محمدابراهیم محجوب"],
    publisher: "انتشارات نشر نو",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghavi-siah.jpg",
    fileUrl: "",
    pages: 450,
    price: 145000,
    discountPrice: 118000,
    rating: { average: 4.2, count: 950 },
    publishedAt: new Date("2014-03-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تفکر سریع و کند",
    slug: "tafakor-sari-kond",
    description:
      "دان دنیل کانمن، برنده جایزه نوبل اقتصاد، سیستم‌های ذهنی انسان را توضیح می‌دهد.",
    type: "ebook",
    categories: ["روانشناسی", "علوم شناختی"],
    authors: ["دنیل کانمن"],
    translators: ["رضا رضایی"],
    publisher: "انتشارات ترجمان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tafakor.jpg",
    fileUrl: "",
    pages: 520,
    price: 165000,
    discountPrice: 139000,
    rating: { average: 4.6, count: 2100 },
    publishedAt: new Date("2019-08-14"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "ملت عشق",
    slug: "mellat-eshgh",
    description:
      "رمانی پرفروش درباره‌ی شمس تبریزی و مولانا که عاشقان بسیاری را مجذوب کرده است.",
    type: "ebook",
    categories: ["رمان", "عاشقانه"],
    authors: ["الیف شافاک"],
    translators: ["ارسلان فصیحی"],
    publisher: "انتشارات ققنوس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/mellat-eshgh.jpg",
    fileUrl: "",
    pages: 510,
    price: 98000,
    discountPrice: 78000,
    rating: { average: 4.7, count: 5400 },
    publishedAt: new Date("2017-12-21"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "جنایت و مکافات",
    slug: "jenayat-mokafat",
    description:
      "شاهکار داستایوفسکی که به بررسی روان انسان در برابر گناه و مجازات می‌پردازد.",
    type: "ebook",
    categories: ["ادبیات", "رمان کلاسیک"],
    authors: ["فئودور داستایوفسکی"],
    translators: ["صالح حسینی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/jenayat.jpg",
    fileUrl: "",
    pages: 670,
    price: 150000,
    discountPrice: 120000,
    rating: { average: 4.9, count: 3100 },
    publishedAt: new Date("2012-10-02"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "بابا لنگ‌دراز",
    slug: "baba-lang-daraz",
    description:
      "رمانی لطیف و پر از امید درباره‌ی دختر یتیمی که با نامه‌هایش زندگی تازه‌ای می‌سازد.",
    type: "ebook",
    categories: ["رمان", "ادبیات نوجوان"],
    authors: ["جین وبستر"],
    translators: ["مریم رضوی"],
    publisher: "انتشارات افق",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/baba-langdaraz.jpg",
    fileUrl: "",
    pages: 240,
    price: 56000,
    discountPrice: 42000,
    rating: { average: 4.6, count: 2700 },
    publishedAt: new Date("2015-01-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "کیمیاگر",
    slug: "kimiagar",
    description:
      "رمان فلسفی پائولو کوئیلو درباره‌ی جستجوی جوانی برای کشف سرنوشت خویش.",
    type: "ebook",
    categories: ["رمان", "معنوی"],
    authors: ["پائولو کوئیلو"],
    translators: ["دل‌آرام وزیری"],
    publisher: "انتشارات کاروان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/kimiagar.jpg",
    fileUrl: "",
    pages: 190,
    price: 69000,
    discountPrice: 54000,
    rating: { average: 4.5, count: 3900 },
    publishedAt: new Date("2010-06-25"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قلعه حیوانات",
    slug: "ghale-heivanat",
    description:
      "تمثیلی سیاسی از جورج اورول که قدرت، فساد و استبداد را نقد می‌کند.",
    type: "ebook",
    categories: ["رمان", "سیاسی"],
    authors: ["جورج اورول"],
    translators: ["امیر امیرشاهی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghale-heivanat.jpg",
    fileUrl: "",
    pages: 160,
    price: 52000,
    discountPrice: 40000,
    rating: { average: 4.4, count: 2300 },
    publishedAt: new Date("2009-04-13"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "1984",
    slug: "1984",
    description:
      "شاهکار اورول که دنیای استبداد و کنترل ذهنی را به تصویر می‌کشد.",
    type: "ebook",
    categories: ["رمان", "سیاسی"],
    authors: ["جورج اورول"],
    translators: ["صالح حسینی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/1984.jpg",
    fileUrl: "",
    pages: 420,
    price: 96000,
    discountPrice: 77000,
    rating: { average: 4.8, count: 5200 },
    publishedAt: new Date("2011-07-19"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "دنیای سوفی",
    slug: "donyaye-sofi",
    description:
      "رمانی فلسفی که مفاهیم اساسی فلسفه غرب را در قالب داستانی جذاب روایت می‌کند.",
    type: "ebook",
    categories: ["فلسفه", "رمان"],
    authors: ["یوستین گردر"],
    translators: ["حسن کامشاد"],
    publisher: "انتشارات هرمس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/donyaye-sofi.jpg",
    fileUrl: "",
    pages: 540,
    price: 140000,
    discountPrice: 115000,
    rating: { average: 4.5, count: 3300 },
    publishedAt: new Date("2013-05-09"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "پیرمرد و دریا",
    slug: "pirmard-darya",
    description:
      "رمان کلاسیک ارنست همینگوی درباره‌ی مبارزه‌ی ماهیگیر پیر با طبیعت.",
    type: "ebook",
    categories: ["ادبیات", "رمان کلاسیک"],
    authors: ["ارنست همینگوی"],
    translators: ["نجف دریابندری"],
    publisher: "انتشارات نگاه",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/pirmard.jpg",
    fileUrl: "",
    pages: 150,
    price: 49000,
    discountPrice: 37000,
    rating: { average: 4.6, count: 2500 },
    publishedAt: new Date("2008-12-18"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "شاهنامه فردوسی",
    slug: "shahnameh-ferdowsi",
    description:
      "حماسه ملی ایرانیان که تاریخ و اسطوره‌های ایران باستان را روایت می‌کند.",
    type: "ebook",
    categories: ["شعر", "ادبیات کلاسیک"],
    authors: ["ابوالقاسم فردوسی"],
    translators: [],
    publisher: "انتشارات علمی فرهنگی",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/shahnameh.jpg",
    fileUrl: "",
    pages: 1200,
    price: 220000,
    discountPrice: 180000,
    rating: { average: 5, count: 6400 },
    publishedAt: new Date("2005-03-30"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "یادداشت‌های زیرزمینی",
    slug: "yaddasht-zirzamini",
    description:
      "یکی از آثار فلسفی-روانی داستایوفسکی که نقدی به انسان مدرن است.",
    type: "ebook",
    categories: ["ادبیات", "فلسفه"],
    authors: ["فئودور داستایوفسکی"],
    translators: ["جهانگیر افکاری"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/zirzamini.jpg",
    fileUrl: "",
    pages: 220,
    price: 75000,
    discountPrice: 60000,
    rating: { average: 4.3, count: 1200 },
    publishedAt: new Date("2015-09-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "بیگانه",
    slug: "biganeh",
    description:
      "شاهکار آلبر کامو که فلسفه پوچ‌گرایی را به‌صورت داستانی روایت می‌کند.",
    type: "ebook",
    categories: ["ادبیات", "فلسفه"],
    authors: ["آلبر کامو"],
    translators: ["لیلی گلستان"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/biganeh.jpg",
    fileUrl: "",
    pages: 210,
    price: 68000,
    discountPrice: 54000,
    rating: { average: 4.4, count: 2200 },
    publishedAt: new Date("2013-02-22"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "برادران کارامازوف",
    slug: "karamazov",
    description: "رمان فلسفی-روانی بزرگ درباره ایمان، اخلاق و خانواده.",
    type: "ebook",
    categories: ["ادبیات", "فلسفه"],
    authors: ["فئودور داستایوفسکی"],
    translators: ["صالح حسینی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/karamazov.jpg",
    fileUrl: "",
    pages: 980,
    price: 180000,
    discountPrice: 145000,
    rating: { average: 4.9, count: 3500 },
    publishedAt: new Date("2016-06-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "کلبه عمو تام",
    slug: "kolbe-amo-tom",
    description: "رمانی تأثیرگذار درباره برده‌داری و آزادی در آمریکا.",
    type: "ebook",
    categories: ["رمان", "تاریخی"],
    authors: ["هریت بیچر استو"],
    translators: ["سروش حبیبی"],
    publisher: "انتشارات علمی فرهنگی",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/kolbe.jpg",
    fileUrl: "",
    pages: 380,
    price: 89000,
    discountPrice: 72000,
    rating: { average: 4.6, count: 1800 },
    publishedAt: new Date("2014-01-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "غرور و تعصب",
    slug: "ghoror-taasob",
    description: "رمان کلاسیک عاشقانه از جین آستن.",
    type: "ebook",
    categories: ["رمان", "عاشقانه"],
    authors: ["جین آستن"],
    translators: ["مینو مشیری"],
    publisher: "انتشارات افق",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/pride.jpg",
    fileUrl: "",
    pages: 420,
    price: 96000,
    discountPrice: 78000,
    rating: { average: 4.7, count: 2600 },
    publishedAt: new Date("2011-09-30"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "مادر",
    slug: "madar",
    description: "رمان اجتماعی حماسی از ماکسیم گورکی.",
    type: "ebook",
    categories: ["رمان", "اجتماعی"],
    authors: ["ماکسیم گورکی"],
    translators: ["ارسلان فصیحی"],
    publisher: "انتشارات نگاه",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/madar.jpg",
    fileUrl: "",
    pages: 480,
    price: 105000,
    discountPrice: 85000,
    rating: { average: 4.4, count: 1400 },
    publishedAt: new Date("2017-04-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "بینوایان",
    slug: "binavayan",
    description: "رمان حماسی و اجتماعی ویکتور هوگو درباره عدالت و آزادی.",
    type: "ebook",
    categories: ["رمان", "تاریخی"],
    authors: ["ویکتور هوگو"],
    translators: ["مهدی سحابی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/lesmis.jpg",
    fileUrl: "",
    pages: 1200,
    price: 240000,
    discountPrice: 190000,
    rating: { average: 4.9, count: 5000 },
    publishedAt: new Date("2009-11-19"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "جنگ و صلح",
    slug: "jang-solt",
    description: "شاهکار لئو تولستوی درباره جنگ ناپلئون و روسیه.",
    type: "ebook",
    categories: ["رمان", "تاریخی"],
    authors: ["لئو تولستوی"],
    translators: ["سروش حبیبی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/warpeace.jpg",
    fileUrl: "",
    pages: 1350,
    price: 260000,
    discountPrice: 210000,
    rating: { average: 5, count: 4700 },
    publishedAt: new Date("2010-02-07"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "آنا کارنینا",
    slug: "anna-karenina",
    description:
      "رمان عاشقانه و اجتماعی تولستوی درباره سرنوشت یک زن در جامعه اشرافی روسیه.",
    type: "ebook",
    categories: ["رمان", "عاشقانه"],
    authors: ["لئو تولستوی"],
    translators: ["سروش حبیبی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/anna.jpg",
    fileUrl: "",
    pages: 960,
    price: 190000,
    discountPrice: 160000,
    rating: { average: 4.8, count: 3100 },
    publishedAt: new Date("2012-08-23"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "دون کیشوت",
    slug: "don-quixote",
    description: "ماجراهای شوالیه خیال‌پرداز اسپانیایی نوشته سروانتس.",
    type: "ebook",
    categories: ["ادبیات کلاسیک", "رمان"],
    authors: ["میگل د سروانتس"],
    translators: ["محمد قاضی"],
    publisher: "انتشارات امیرکبیر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/don.jpg",
    fileUrl: "",
    pages: 870,
    price: 175000,
    discountPrice: 140000,
    rating: { average: 4.7, count: 2800 },
    publishedAt: new Date("2007-10-28"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "پدر پولدار، پدر بی‌پول",
    slug: "rich-dad-poor-dad",
    description:
      "راهنمای ثروت و مدیریت مالی برای نسل جدید نوشته رابرت کیوساکی.",
    type: "ebook",
    categories: ["کسب و کار", "اقتصاد"],
    authors: ["رابرت کیوساکی"],
    translators: ["شهرام شریف"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/rich-dad.jpg",
    fileUrl: "",
    pages: 295,
    price: 99000,
    discountPrice: 79000,
    rating: { average: 4.7, count: 6800 },
    publishedAt: new Date("2013-09-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قدرت اکنون",
    slug: "power-of-now",
    description: "راهنمایی معنوی اکهارت تله برای زندگی در لحظه‌ی حال.",
    type: "ebook",
    categories: ["معنویت", "روانشناسی"],
    authors: ["اکهارت تله"],
    translators: ["مهسا ملک مرزبان"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/power-now.jpg",
    fileUrl: "",
    pages: 280,
    price: 125000,
    discountPrice: 102000,
    rating: { average: 4.8, count: 7400 },
    publishedAt: new Date("2012-08-17"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "ملت عشق",
    slug: "mellat-eshgh",
    description:
      "رمانی پرفروش درباره‌ی شمس تبریزی و مولانا نوشته‌ی الیف شافاک.",
    type: "ebook",
    categories: ["رمان", "معنوی"],
    authors: ["الیف شافاک"],
    translators: ["ارسلان فصیحی"],
    publisher: "انتشارات ققنوس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/mellat-eshgh.jpg",
    fileUrl: "",
    pages: 510,
    price: 98000,
    discountPrice: 78000,
    rating: { average: 4.7, count: 5400 },
    publishedAt: new Date("2017-12-21"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "کیمیاگر",
    slug: "kimiagar",
    description:
      "رمان فلسفی پائولو کوئیلو درباره جستجوی جوانی برای کشف سرنوشت خویش.",
    type: "ebook",
    categories: ["رمان", "معنوی"],
    authors: ["پائولو کوئیلو"],
    translators: ["دل‌آرام وزیری"],
    publisher: "انتشارات کاروان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/kimiagar.jpg",
    fileUrl: "",
    pages: 190,
    price: 69000,
    discountPrice: 54000,
    rating: { average: 4.5, count: 3900 },
    publishedAt: new Date("2010-06-25"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "هری پاتر و سنگ جادو",
    slug: "harry-potter-1",
    description:
      "اولین جلد از مجموعه‌ی پرطرفدار هری پاتر نوشته جی. کی. رولینگ.",
    type: "ebook",
    categories: ["فانتزی", "رمان"],
    authors: ["جی. کی. رولینگ"],
    translators: ["ویدا اسلامیه"],
    publisher: "انتشارات کتابسرای تندیس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/harry-potter-1.jpg",
    fileUrl: "",
    pages: 340,
    price: 140000,
    discountPrice: 115000,
    rating: { average: 4.9, count: 15400 },
    publishedAt: new Date("2005-05-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "دنیای سوفی",
    slug: "donyaye-sofi",
    description:
      "رمانی فلسفی که مفاهیم اساسی فلسفه غرب را در قالب داستانی جذاب روایت می‌کند.",
    type: "ebook",
    categories: ["فلسفه", "رمان"],
    authors: ["یوستین گردر"],
    translators: ["حسن کامشاد"],
    publisher: "انتشارات هرمس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/donyaye-sofi.jpg",
    fileUrl: "",
    pages: 540,
    price: 140000,
    discountPrice: 115000,
    rating: { average: 4.5, count: 3300 },
    publishedAt: new Date("2013-05-09"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "ملت عشق 2",
    slug: "mellat-eshgh-2",
    description: "ادامه داستان معنوی و عاشقانه درباره‌ی شمس و مولانا.",
    type: "ebook",
    categories: ["رمان", "معنوی"],
    authors: ["الیف شافاک"],
    translators: ["ارسلان فصیحی"],
    publisher: "انتشارات ققنوس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/mellat-eshgh-2.jpg",
    fileUrl: "",
    pages: 500,
    price: 98000,
    discountPrice: 80000,
    rating: { average: 4.7, count: 4200 },
    publishedAt: new Date("2018-03-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قوی سیاه",
    slug: "ghavi-siah-2",
    description:
      "کتابی درباره‌ی رویدادهای پیش‌بینی‌ناپذیر و تاثیر عظیم آن‌ها بر جهان.",
    type: "ebook",
    categories: ["اقتصاد", "فلسفه"],
    authors: ["نسیم نیکلاس طالب"],
    translators: ["محمدابراهیم محجوب"],
    publisher: "انتشارات نشر نو",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghavi-siah-2.jpg",
    fileUrl: "",
    pages: 450,
    price: 145000,
    discountPrice: 118000,
    rating: { average: 4.2, count: 950 },
    publishedAt: new Date("2014-03-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "ذهن موفق",
    slug: "zehn-movafagh",
    description: "کتابی درباره تکنیک‌های روانشناسی موفقیت و انگیزه",
    type: "ebook",
    categories: ["روانشناسی", "موفقیت"],
    authors: ["کارول دوک"],
    translators: ["آزیتا رحیمی"],
    publisher: "انتشارات نوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/zehn-movafagh.jpg",
    fileUrl: "",
    pages: 320,
    price: 120000,
    discountPrice: 95000,
    rating: { average: 4.6, count: 1300 },
    publishedAt: new Date("2016-05-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "هوش هیجانی",
    slug: "hoosh-hijani",
    description: "راهنمایی برای درک و کنترل احساسات و بهبود روابط",
    type: "ebook",
    categories: ["روانشناسی"],
    authors: ["دانیل گلمن"],
    translators: ["مهسا ملک مرزبان"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/hoosh-hijani.jpg",
    fileUrl: "",
    pages: 368,
    price: 135000,
    discountPrice: 110000,
    rating: { average: 4.7, count: 2100 },
    publishedAt: new Date("2015-03-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "چه کسی پنیر مرا جابجا کرد",
    slug: "che-kasi-panir-mar-jabza-kard",
    description: "داستانی کوتاه با درس‌های زندگی و تغییر",
    type: "ebook",
    categories: ["موفقیت", "روانشناسی"],
    authors: ["اسپنسر جانسون"],
    translators: ["سحر صادقی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/panir.jpg",
    fileUrl: "",
    pages: 112,
    price: 48000,
    discountPrice: 38000,
    rating: { average: 4.5, count: 1700 },
    publishedAt: new Date("2013-11-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "راز",
    slug: "raz",
    description: "کتابی درباره قدرت فکر مثبت و قانون جذب",
    type: "ebook",
    categories: ["موفقیت", "معنویت"],
    authors: ["راندا برن"],
    translators: ["مهرداد رستمی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/raz.jpg",
    fileUrl: "",
    pages: 220,
    price: 88000,
    discountPrice: 69000,
    rating: { average: 4.6, count: 3100 },
    publishedAt: new Date("2012-02-14"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "مدیر یک دقیقه‌ای",
    slug: "modir-1-minute",
    description: "کتابی کوتاه درباره رهبری و مدیریت مؤثر",
    type: "ebook",
    categories: ["کسب و کار", "مدیریت"],
    authors: ["کن بلانچارد"],
    translators: ["فرزانه ملکی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/modir1.jpg",
    fileUrl: "",
    pages: 112,
    price: 65000,
    discountPrice: 52000,
    rating: { average: 4.5, count: 1900 },
    publishedAt: new Date("2011-07-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "از خوب به عالی",
    slug: "az-khoob-be-ali",
    description: "راهنمای تحول سازمان‌ها و افراد به سطح عالی",
    type: "ebook",
    categories: ["کسب و کار", "موفقیت"],
    authors: ["جیم کالینز"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/good-to-great.jpg",
    fileUrl: "",
    pages: 320,
    price: 140000,
    discountPrice: 115000,
    rating: { average: 4.8, count: 2800 },
    publishedAt: new Date("2007-04-30"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "هفت عادت مردمان موثر",
    slug: "haft-adat",
    description: "کتابی مشهور درباره توسعه فردی و کارآمدی در زندگی و کار",
    type: "ebook",
    categories: ["موفقیت", "خودشناسی"],
    authors: ["استفان کاوی"],
    translators: ["علیرضا حیدری"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/haft-adat.jpg",
    fileUrl: "",
    pages: 384,
    price: 155000,
    discountPrice: 125000,
    rating: { average: 4.9, count: 4500 },
    publishedAt: new Date("2004-09-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "مدیریت بحران",
    slug: "modiriyat-bazm",
    description: "کتابی کاربردی درباره مدیریت و مقابله با بحران‌های سازمانی",
    type: "ebook",
    categories: ["مدیریت", "کسب و کار"],
    authors: ["پیتر دراکر"],
    translators: ["محسن کاظمی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/crisis.jpg",
    fileUrl: "",
    pages: 280,
    price: 98000,
    discountPrice: 76000,
    rating: { average: 4.6, count: 2100 },
    publishedAt: new Date("2009-05-18"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تجارت به سبک نیویورک",
    slug: "tejarat-newyork",
    description: "راهنمای کسب و کار و کارآفرینی در دنیای مدرن",
    type: "ebook",
    categories: ["کسب و کار", "کارآفرینی"],
    authors: ["ریچارد برانسون"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tejarat.jpg",
    fileUrl: "",
    pages: 220,
    price: 99000,
    discountPrice: 77000,
    rating: { average: 4.7, count: 1300 },
    publishedAt: new Date("2013-08-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قانون جذب",
    slug: "ghanoon-jazb",
    description: "راهنمای عملی استفاده از قانون جذب برای رسیدن به اهداف",
    type: "ebook",
    categories: ["موفقیت", "معنویت"],
    authors: ["مایکل لوییس"],
    translators: ["فریبا صمدی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghanoon-jazb.jpg",
    fileUrl: "",
    pages: 200,
    price: 78000,
    discountPrice: 62000,
    rating: { average: 4.6, count: 1600 },
    publishedAt: new Date("2012-06-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "آدم خوب",
    slug: "adam-khoob",
    description: "رمانی کوتاه درباره اخلاق و انتخاب‌های زندگی",
    type: "ebook",
    categories: ["رمان", "اخلاق"],
    authors: ["جان استاین‌بک"],
    translators: ["سعید معمار"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/adam-khoob.jpg",
    fileUrl: "",
    pages: 220,
    price: 72000,
    discountPrice: 58000,
    rating: { average: 4.5, count: 1400 },
    publishedAt: new Date("2010-01-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "زندگی شاد",
    slug: "zendegi-shad",
    description: "کتابی درباره‌ی روانشناسی مثبت و شاد زیستن",
    type: "ebook",
    categories: ["روانشناسی", "موفقیت"],
    authors: ["مارتین سلیگمن"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات نوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/zendegi-shad.jpg",
    fileUrl: "",
    pages: 300,
    price: 110000,
    discountPrice: 90000,
    rating: { average: 4.7, count: 2300 },
    publishedAt: new Date("2014-03-01"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "هنر شفاف اندیشیدن",
    slug: "honar-shafaf-andishidan",
    description: "راهنمای تصمیم‌گیری بهتر و شناخت خطاهای ذهنی",
    type: "ebook",
    categories: ["روانشناسی", "فلسفه"],
    authors: ["رولف دوبلی"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات کاروان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/shafaf-andishidan.jpg",
    fileUrl: "",
    pages: 320,
    price: 98000,
    discountPrice: 78000,
    rating: { average: 4.6, count: 2000 },
    publishedAt: new Date("2013-09-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "زندگی زیباست",
    slug: "zendegi-ziba",
    description: "داستان کوتاه و آموزنده درباره امید و شجاعت",
    type: "ebook",
    categories: ["رمان", "الهام‌بخش"],
    authors: ["ویکتور فرانکل"],
    translators: ["حسین قراچه‌داغی"],
    publisher: "انتشارات پیام امروز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/zendegi-ziba.jpg",
    fileUrl: "",
    pages: 190,
    price: 65000,
    discountPrice: 52000,
    rating: { average: 4.8, count: 1800 },
    publishedAt: new Date("2011-04-22"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "راز موفقیت",
    slug: "raz-movafaghiyat",
    description: "کتابی درباره اصول موفقیت و رسیدن به اهداف بزرگ",
    type: "ebook",
    categories: ["موفقیت", "کسب و کار"],
    authors: ["برایان تریسی"],
    translators: ["آرزو حسینی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/raz-movafaghiyat.jpg",
    fileUrl: "",
    pages: 260,
    price: 99000,
    discountPrice: 79000,
    rating: { average: 4.7, count: 2200 },
    publishedAt: new Date("2010-08-18"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "خودت را به فنا نده",
    slug: "khodet-ra-fana-nakone",
    description: "راهنمایی برای شناخت توانایی‌ها و مدیریت زندگی",
    type: "ebook",
    categories: ["روانشناسی", "خودشناسی"],
    authors: ["مارک منسون"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات میلکان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/khodet-ra.jpg",
    fileUrl: "",
    pages: 250,
    price: 88000,
    discountPrice: 70000,
    rating: { average: 4.5, count: 3200 },
    publishedAt: new Date("2018-02-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قدرت تمرکز",
    slug: "ghodrat-tamarkoz",
    description: "تمرینات و تکنیک‌های افزایش تمرکز و بازدهی ذهن",
    type: "ebook",
    categories: ["روانشناسی", "خودشناسی"],
    authors: ["جک کانفیلد"],
    translators: ["آزیتا رحیمی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghodrat-tamarkoz.jpg",
    fileUrl: "",
    pages: 230,
    price: 72000,
    discountPrice: 58000,
    rating: { average: 4.6, count: 1400 },
    publishedAt: new Date("2013-05-01"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "جادوی تفکر بزرگ",
    slug: "jadoye-tafakor-bozorg",
    description: "کتابی کلاسیک درباره موفقیت و تغییر نگرش",
    type: "ebook",
    categories: ["موفقیت", "خودشناسی"],
    authors: ["دیوید شوارتز"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/jadoye-tafakor.jpg",
    fileUrl: "",
    pages: 280,
    price: 89000,
    discountPrice: 69000,
    rating: { average: 4.7, count: 2100 },
    publishedAt: new Date("2010-09-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "ایده عالی",
    slug: "ideh-ali",
    description: "راهنمای عملی برای پیدا کردن و اجرای ایده‌های نو",
    type: "ebook",
    categories: ["کسب و کار", "کارآفرینی"],
    authors: ["استیو بلنک"],
    translators: ["فرزانه ملکی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ideh-ali.jpg",
    fileUrl: "",
    pages: 220,
    price: 95000,
    discountPrice: 78000,
    rating: { average: 4.5, count: 1300 },
    publishedAt: new Date("2015-06-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تاریخ تمدن",
    slug: "tarikh-tamadon",
    description: "کتابی جامع درباره تاریخ تمدن‌ها و فرهنگ‌های بشری",
    type: "ebook",
    categories: ["تاریخ", "اجتماعی"],
    authors: ["ویل دورانت"],
    translators: ["حسینعلی آذر"],
    publisher: "انتشارات ققنوس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tarikh-tamadon.jpg",
    fileUrl: "",
    pages: 900,
    price: 220000,
    discountPrice: 180000,
    rating: { average: 4.8, count: 3100 },
    publishedAt: new Date("2010-03-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تاریخچه علم",
    slug: "tarikhche-elm",
    description: "روند پیشرفت علم از گذشته تا امروز",
    type: "ebook",
    categories: ["تاریخ", "علم"],
    authors: ["جان گریفیت"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات کاروان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tarikhche-elm.jpg",
    fileUrl: "",
    pages: 450,
    price: 130000,
    discountPrice: 105000,
    rating: { average: 4.6, count: 900 },
    publishedAt: new Date("2012-09-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "انسان در جستجوی معنا",
    slug: "ensan-dar-jostoju-ye-mana",
    description: "داستان و تحلیل زندگی و فلسفه ویکتور فرانکل",
    type: "ebook",
    categories: ["روانشناسی", "معنویت"],
    authors: ["ویکتور فرانکل"],
    translators: ["حسین قراچه‌داغی"],
    publisher: "انتشارات پیام امروز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ensan-mana.jpg",
    fileUrl: "",
    pages: 230,
    price: 88000,
    discountPrice: 70000,
    rating: { average: 4.9, count: 4100 },
    publishedAt: new Date("2011-05-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تاریخ فلسفه",
    slug: "tarikh-falsafe",
    description: "مروری جامع بر فلسفه از یونان باستان تا امروز",
    type: "ebook",
    categories: ["فلسفه", "تاریخ"],
    authors: ["برتراند راسل"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات نوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tarikh-falsafe.jpg",
    fileUrl: "",
    pages: 750,
    price: 195000,
    discountPrice: 155000,
    rating: { average: 4.7, count: 2800 },
    publishedAt: new Date("2013-02-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "انقلاب صنعتی",
    slug: "enghelab-sanat",
    description: "تاریخ و تاثیر انقلاب صنعتی در جهان",
    type: "ebook",
    categories: ["تاریخ", "اقتصاد"],
    authors: ["اریک هابسبام"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات ققنوس",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/enghelab-sanat.jpg",
    fileUrl: "",
    pages: 410,
    price: 145000,
    discountPrice: 118000,
    rating: { average: 4.6, count: 1200 },
    publishedAt: new Date("2010-08-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "رازهای موفقیت افراد ثروتمند",
    slug: "raz-movafaghiyat-thorvatmand",
    description: "کتابی درباره ذهنیت و عادت‌های افراد موفق و ثروتمند",
    type: "ebook",
    categories: ["موفقیت", "کسب و کار"],
    authors: ["ناپلئون هیل"],
    translators: ["آرزو حسینی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/raz-thorvatmand.jpg",
    fileUrl: "",
    pages: 310,
    price: 98000,
    discountPrice: 78000,
    rating: { average: 4.8, count: 2500 },
    publishedAt: new Date("2011-07-18"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "مدیریت زمان",
    slug: "modiriyat-zaman",
    description: "راهنمایی کاربردی برای استفاده بهینه از زمان و انرژی",
    type: "ebook",
    categories: ["موفقیت", "خودشناسی"],
    authors: ["برایان تریسی"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/modiriyat-zaman.jpg",
    fileUrl: "",
    pages: 220,
    price: 78000,
    discountPrice: 60000,
    rating: { average: 4.6, count: 1300 },
    publishedAt: new Date("2012-09-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "راه هنر زندگی",
    slug: "rah-honar-zendegi",
    description: "راهنمایی برای زندگی بهتر و خلاقانه",
    type: "ebook",
    categories: ["خودشناسی", "موفقیت"],
    authors: ["ارنست هینکل"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/rah-honar.jpg",
    fileUrl: "",
    pages: 260,
    price: 98000,
    discountPrice: 79000,
    rating: { average: 4.7, count: 1200 },
    publishedAt: new Date("2014-06-01"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "فلسفه زندگی",
    slug: "falsafe-zendegi",
    description: "بررسی دیدگاه‌های فلسفی مختلف درباره زندگی و معنا",
    type: "ebook",
    categories: ["فلسفه", "معنویت"],
    authors: ["آلن دوباتن"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات نوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/falsafe-zendegi.jpg",
    fileUrl: "",
    pages: 340,
    price: 125000,
    discountPrice: 98000,
    rating: { average: 4.5, count: 900 },
    publishedAt: new Date("2015-03-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "روانشناسی پول",
    slug: "ravanshenasi-pol",
    description: "تحلیل رفتار انسان‌ها با پول و روش‌های مالی موفق",
    type: "ebook",
    categories: ["روانشناسی", "اقتصاد"],
    authors: ["مورگان هاوزل"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ravanshenasi-pol.jpg",
    fileUrl: "",
    pages: 250,
    price: 95000,
    discountPrice: 75000,
    rating: { average: 4.6, count: 1600 },
    publishedAt: new Date("2018-01-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "کسب و کار از صفر",
    slug: "kasb-o-kar-az-sefr",
    description: "راهنمای عملی راه‌اندازی کسب‌وکار بدون سرمایه زیاد",
    type: "ebook",
    categories: ["کسب و کار", "کارآفرینی"],
    authors: ["کریس گیلبو"],
    translators: ["فرزانه ملکی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/kasb-o-kar.jpg",
    fileUrl: "",
    pages: 280,
    price: 99000,
    discountPrice: 78000,
    rating: { average: 4.7, count: 1400 },
    publishedAt: new Date("2017-08-05"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "قدرت عادت",
    slug: "ghodrat-adat",
    description: "چگونه عادت‌ها زندگی و موفقیت ما را شکل می‌دهند",
    type: "ebook",
    categories: ["روانشناسی", "موفقیت"],
    authors: ["چارلز دوهیگ"],
    translators: ["آزیتا رحیمی"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ghodrat-adat.jpg",
    fileUrl: "",
    pages: 350,
    price: 120000,
    discountPrice: 95000,
    rating: { average: 4.8, count: 2300 },
    publishedAt: new Date("2014-11-22"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "روانشناسی موفقیت",
    slug: "ravanshenasi-movafaghiyat",
    description: "اصول روانشناسی برای رسیدن به موفقیت فردی و حرفه‌ای",
    type: "ebook",
    categories: ["روانشناسی", "موفقیت"],
    authors: ["جیمز کلیر"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage:
      "https://www.ketabrah.ir/img/books/ravanshenasi-movafaghiyat.jpg",
    fileUrl: "",
    pages: 320,
    price: 115000,
    discountPrice: 90000,
    rating: { average: 4.7, count: 1800 },
    publishedAt: new Date("2016-04-15"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تفکر خلاق",
    slug: "tafakor-khalagh",
    description: "روش‌ها و تمرینات برای افزایش خلاقیت و نوآوری",
    type: "ebook",
    categories: ["خودشناسی", "روانشناسی"],
    authors: ["ادوارد دوبونو"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات کاروان",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tafakor-khalagh.jpg",
    fileUrl: "",
    pages: 250,
    price: 88000,
    discountPrice: 68000,
    rating: { average: 4.6, count: 1200 },
    publishedAt: new Date("2013-07-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "تاریخ ایران",
    slug: "tarikh-iran",
    description: "نگاهی جامع به تاریخ ایران از باستان تا معاصر",
    type: "ebook",
    categories: ["تاریخ", "اجتماعی"],
    authors: ["رضا شاهی"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات نیلوفر",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/tarikh-iran.jpg",
    fileUrl: "",
    pages: 480,
    price: 140000,
    discountPrice: 110000,
    rating: { average: 4.5, count: 900 },
    publishedAt: new Date("2012-02-20"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "فرهنگ لغات موفقیت",
    slug: "farhang-lughat-movafaghiyat",
    description: "کتابی کاربردی برای بهبود مهارت‌ها و ذهنیت موفقیت",
    type: "ebook",
    categories: ["موفقیت", "خودشناسی"],
    authors: ["برایان تریسی"],
    translators: ["آرزو حسینی"],
    publisher: "انتشارات نسل نواندیش",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/farhang-lughat.jpg",
    fileUrl: "",
    pages: 210,
    price: 72000,
    discountPrice: 58000,
    rating: { average: 4.6, count: 1000 },
    publishedAt: new Date("2015-01-12"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "کتاب زندگی",
    slug: "ketab-zendegi",
    description: "مجموعه‌ای از داستان‌ها و درس‌های زندگی واقعی",
    type: "ebook",
    categories: ["رمان", "الهام‌بخش"],
    authors: ["اریکا جونگ"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات پیام امروز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ketab-zendegi.jpg",
    fileUrl: "",
    pages: 280,
    price: 98000,
    discountPrice: 78000,
    rating: { average: 4.7, count: 1300 },
    publishedAt: new Date("2014-08-10"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "اقتصاد برای همه",
    slug: "eqtesad-baraye-hame",
    description: "راهنمای ساده و کاربردی برای درک اصول اقتصاد",
    type: "ebook",
    categories: ["اقتصاد", "کسب و کار"],
    authors: ["تیم هارفورد"],
    translators: ["مهسا ملکی"],
    publisher: "انتشارات آوین",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/eqtesad-baraye-hame.jpg",
    fileUrl: "",
    pages: 320,
    price: 115000,
    discountPrice: 90000,
    rating: { average: 4.5, count: 1400 },
    publishedAt: new Date("2016-03-22"),
    reviews: [],
    inCarts: [],
  },
  {
    title: "روانشناسی موفقیت شغلی",
    slug: "ravanshenasi-shoghli",
    description: "تکنیک‌ها و راهکارهای موفقیت در محیط کار",
    type: "ebook",
    categories: ["روانشناسی", "کسب و کار"],
    authors: ["جیمز کلیر"],
    translators: ["سارا برزگری"],
    publisher: "انتشارات ذهن‌آویز",
    language: "fa",
    coverImage: "https://www.ketabrah.ir/img/books/ravanshenasi-shoghli.jpg",
    fileUrl: "",
    pages: 300,
    price: 99000,
    discountPrice: 78000,
    rating: { average: 4.6, count: 1200 },
    publishedAt: new Date("2017-02-15"),
    reviews: [],
    inCarts: [],
  },
];
